controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster # why does it break??

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController